---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by duoyi.
--- DateTime: 2020/8/11 20:05

---@class Image
local Image = class()

function Image:ctor(...)
    print("Image ctor",...)
end

function Image:Show()
    print("image show",self)
end

return Image