---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by duoyi.
--- DateTime: 2020/8/11 20:05
---

local Image = require("game/image")

---@class RawImage : Image 只是class类型声明
local RawImage = class(Image)

function RawImage:Show()

    print("RawImage show ----image:",Image,Image.Show,inspect(Image))
    Image.Show(self)
    print("RawImage show",self,self.Show,self.super)
end

return RawImage